# Generated by Django 4.1.7 on 2023-05-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vCash_Num', models.CharField(help_text='Enter 11 numbers "EX: 01XXXXXXXXX"', max_length=11)),
                ('bankAccount_Num', models.CharField(help_text='Enter 16 numbers "EX: XXXX-XXXX-XXXX-XXXX"', max_length=19)),
            ],
        ),
    ]
