# Generated by Django 4.1.7 on 2023-03-12 19:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaysCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_update_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 21, 58, 31, 351611))),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=50, null='')),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('gender', models.IntegerField(choices=[(1, 'Male'), (2, 'Female')])),
                ('duration', models.IntegerField(choices=[(1, '1 Month'), (3, '3 Months'), (6, '6 Months')])),
                ('goal', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('height', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('waist_circumference', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('arm_circumference', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('chest_circumference', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('food_allergy', models.CharField(max_length=350)),
                ('dieseases', models.CharField(max_length=350)),
                ('surgeries', models.CharField(max_length=3050)),
                ('drugs_or_supplements', models.TextField(max_length=300)),
                ('food_you_do_not_like', models.TextField(max_length=300)),
                ('food_you_like', models.TextField(max_length=300)),
                ('how_many_meals_do_you_want', models.IntegerField(choices=[(3, '3 Meals'), (4, '4 Meals'), (5, '5 Meals'), (6, '6 Meals')])),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='EG')),
                ('expiration_date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('latest_plan_sent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registration.dayscountdown')),
            ],
        ),
    ]
