# Generated by Django 4.1.7 on 2023-05-07 11:08

import datetime
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('email', models.EmailField(default='', max_length=254)),
                ('age', models.IntegerField()),
                ('job', models.CharField(max_length=50, null='')),
                ('relationship_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married')], default='single', max_length=10)),
                ('goal', models.TextField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('height', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('chest_circumference', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('waist_circumference', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('arm_circumference', models.DecimalField(decimal_places=2, max_digits=1000)),
                ('food_allergy', models.CharField(max_length=350)),
                ('dieseases', models.CharField(max_length=350)),
                ('surgeries', models.CharField(max_length=3050)),
                ('drugs_or_supplements', models.TextField(max_length=300)),
                ('food_you_like', models.TextField(max_length=300)),
                ('food_you_do_not_like', models.TextField(max_length=300)),
                ('number_of_meals', models.CharField(choices=[('three', '3'), ('four', '4'), ('five', '5'), ('six', '6')], default='three', max_length=10)),
                ('is_this_your_first_diet', models.CharField(choices=[('yes', 'Yes'), ('no', 'NO')], default='yes', max_length=10)),
                ('package', models.CharField(choices=[('basic', 'Basic'), ('advanced', 'Advanced'), ('premium', 'Premium')], default='advanced', max_length=10)),
                ('start_date', models.DateField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='EG')),
                ('expiration_date', models.DateField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('plan_update_date', models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 7, 14, 8, 24, 83969))),
            ],
        ),
    ]
