# Generated by Django 4.1.7 on 2023-03-12 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_dayscountdown_plan_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayscountdown',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=1),
        ),
    ]
