# Generated by Django 4.1.7 on 2023-05-07 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0002_alter_client_plan_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 7, 14, 8, 46, 574731)),
        ),
    ]
