# Generated by Django 4.1.7 on 2023-05-18 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0007_alter_client_plan_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 5, 18, 15, 9, 20, 704375)),
        ),
    ]
