# Generated by Django 4.1.7 on 2023-03-12 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0009_remove_client_latest_plan_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaysCountdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 22, 24, 18, 812757)),
        ),
        migrations.AddField(
            model_name='client',
            name='latest_plan_sent',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Registration.dayscountdown'),
            preserve_default=False,
        ),
    ]
