# Generated by Django 4.1.7 on 2023-03-12 20:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0010_dayscountdown_alter_client_plan_update_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='latest_plan_sent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Registration.dayscountdown'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 22, 26, 47, 413268)),
        ),
    ]
