# Generated by Django 4.1.7 on 2023-03-12 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0011_alter_client_latest_plan_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='latest_plan_sent',
        ),
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 12, 22, 32, 32, 958029)),
        ),
        migrations.DeleteModel(
            name='DaysCountdown',
        ),
    ]
