# Generated by Django 4.1.7 on 2023-04-18 16:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0012_remove_client_latest_plan_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 18, 18, 9, 36, 311007)),
        ),
    ]
