# Generated by Django 4.1.7 on 2023-04-26 07:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0020_alter_client_plan_update_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan_update_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 26, 9, 57, 44, 470218)),
        ),
    ]
