# Generated by Django 4.1.7 on 2023-05-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=150)),
                ('video_link', models.URLField()),
                ('Video_name', models.CharField(max_length=100)),
            ],
        ),
    ]
