# Generated by Django 4.1.7 on 2023-03-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=150)),
                ('video_link', models.URLField(max_length=250)),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
    ]
