# Generated by Django 4.1.7 on 2023-03-10 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0002_alter_reel_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='video_link',
            field=models.TextField(),
        ),
    ]
