# Generated by Django 4.1.7 on 2023-03-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0004_alter_reel_video_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='video_number',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reel',
            name='video_link',
            field=models.TextField(),
        ),
    ]
