# Generated by Django 4.1.7 on 2023-03-10 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0005_reel_video_number_alter_reel_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='video_number',
        ),
    ]
