# Generated by Django 4.1.7 on 2023-03-10 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0006_remove_reel_video_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reel',
            old_name='video_name',
            new_name='number',
        ),
    ]
