# Generated by Django 4.1.7 on 2023-03-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0007_rename_video_name_reel_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='visible',
        ),
        migrations.AddField(
            model_name='reel',
            name='Video_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reel',
            name='video_link',
            field=models.URLField(),
        ),
    ]
