# Generated by Django 4.1.7 on 2023-03-10 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0008_remove_reel_visible_reel_video_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reel',
            new_name='Home_Videos',
        ),
    ]
