# Generated by Django 4.1.7 on 2023-03-10 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Media', '0010_rename_home_videos_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Home',
            new_name='Reel',
        ),
    ]
